/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Tugas01;

public class App {
    public static void main(String[] args) throws Exception {
        PasswordStore pass1 = new PasswordStore("Wahyu", "12345", "whyyy");
        pass1.setCategory(PasswordStore.CAT_WEBAPP);
        System.out.println(pass1);
        System.out.println("USERNAME: "+pass1.username+" PASSWORD: "+pass1.getPassword());
    }
}
